[package]
name = "solores"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
env_logger = "0.10.0"
prettyplease = "0.1.21"
log = "0.4.17"
quote = "^1.0"
semver = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.89"
syn = "^1.0"
toml = "0.5.9"

[dev-dependencies]
assert_cmd = "2.0.7"