[workspace]
resolver = "2"

members = [
    "examples/anchor/ix_no_args/*",
    "examples/anchor/ix_no_privilege/*",
    "examples/anchor/drift/*",
    "examples/anchor/marinade/*",
    "examples/anchor/unstake_it/*",
    "examples/shank/ix_no_args/*",
    "examples/shank/ix_no_privilege/*",
    "examples/shank/phoenix_v1/*",
    "examples/shank/token_metadata/*",
    "solores",
    "test_utils"
]

[workspace.dependencies]
borsh = "^0.10"
bytemuck = "^1"
lazy_static = "^1"
num-derive = "^0.3"
num-traits = "^0.2"
serde = "^1"
serde_json = "^1"
solana-cli-config = "^1"
solana-client = "^1"
solana-program = "^1"
solana-sdk = "^1"
thiserror = "^1.0"
tokio = "^1"