[package]
name = "solores"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
env_logger = "0.10.0"
heck = "^0.4.0"
itertools = "^0.10"
prettyplease = "0.1.21"
log = "0.4.17"
log-panics = { version = "2", features = ["with-backtrace"]}
proc-macro2 = "^1.0"
quote = "^1.0"
semver = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.89"
syn = { version = "^1.0", features = ["full"] }
toml = "0.5.9"
void = "^1.0"

[dev-dependencies]
assert_cmd = "2.0.7"