[package]
name = "drift_interface"
version = "2.10.0"
edition = "2021"

[dependencies]
borsh = { version = "^0.9", features = ["const-generics"] }
solana-program = "^1.9"
thiserror = "^1.0"
num-derive = "^0.3"
num-traits = "^0.2"
