[package]
name = "mpl_token_metadata_interface"
version = "1.2.5"
edition = "2021"

[dependencies]
borsh = "^0.9"
solana-program = "^1.9,<1.16"
thiserror = "^1.0"
num-derive = "^0.3"
num-traits = "^0.2"

[dependencies.serde]
optional = true
version = "^1.0"
